name: deployment

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:

        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2

        - name: Copy Files
          run: rsync -a /root/actions-runner-lms/_work/lmsportal/lmsportal/ /var/www/lmsportal/ 

        - name: Give permission
        - run: chmod -R 775 /var/www/lmsportal/

        - name: Install Dependencies
        - run: npm install --prefix /var/www/lmsportal